starting worker pid=18300 on localhost:11865 at 01:16:12.655
starting worker pid=14624 on localhost:11865 at 01:16:12.837
starting worker pid=11900 on localhost:11865 at 01:16:13.022
starting worker pid=17932 on localhost:11865 at 01:16:13.240
starting worker pid=10436 on localhost:11865 at 01:16:13.415
starting worker pid=3304 on localhost:11865 at 01:16:13.590
starting worker pid=15240 on localhost:11865 at 01:16:13.784
starting worker pid=13300 on localhost:11865 at 01:16:13.964
starting worker pid=6820 on localhost:11879 at 01:17:49.706
starting worker pid=16316 on localhost:11879 at 01:17:50.243
starting worker pid=12112 on localhost:11879 at 01:17:50.565
starting worker pid=18940 on localhost:11879 at 01:17:51.045
starting worker pid=10832 on localhost:11879 at 01:17:51.408
starting worker pid=17800 on localhost:11879 at 01:17:51.853
starting worker pid=18820 on localhost:11879 at 01:17:52.304
starting worker pid=12188 on localhost:11879 at 01:17:52.708
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
starting worker pid=14880 on localhost:11879 at 02:21:10.222
starting worker pid=17148 on localhost:11879 at 02:21:10.408
starting worker pid=9196 on localhost:11879 at 02:21:10.592
starting worker pid=9636 on localhost:11879 at 02:21:10.761
starting worker pid=19080 on localhost:11879 at 02:21:10.936
starting worker pid=17172 on localhost:11879 at 02:21:11.112
starting worker pid=19196 on localhost:11879 at 02:21:11.290
starting worker pid=6356 on localhost:11879 at 02:21:11.464
